version: master-{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
clone_folder: c:\projects\openscap

environment:
  matrix:
    - PYTHON_VERSION: 36

init:
- set PATH=C:\Python%PYTHON_VERSION%;%PYTHON%\Scripts;%PATH%

install:
- choco install swig
- choco install doxygen.install graphviz
- cmd: vcpkg install curl libxml2 libxslt bzip2 pcre pthreads

cache: c:\tools\vcpkg\installed\

before_build:
- cmd: >-
    cd build

    cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake ..

build:
  project: c:\projects\openscap\build\openscap.sln
  verbosity: minimal
